In [9]:
import numpy as np

In [10]:
data = [
    [293,1.6,851],
    [230,15.5,816],
    [172,22.0,1058],
    [91,43.0,1201],
    [113,33.0,1357],
    [125,40.0,1115],
]
data = np.array(data)
y = data[:,0]
x = data[:,1:]
x = np.column_stack((np.ones(x.shape[0]),x))
x

array([[1.000e+00, 1.600e+00, 8.510e+02],
       [1.000e+00, 1.550e+01, 8.160e+02],
       [1.000e+00, 2.200e+01, 1.058e+03],
       [1.000e+00, 4.300e+01, 1.201e+03],
       [1.000e+00, 3.300e+01, 1.357e+03],
       [1.000e+00, 4.000e+01, 1.115e+03]])

In [11]:
def multivariate_regression (x,y):
    a = x.T@x
    a_inv = np.linalg.inv(a)
    b = x.T@y
    return a_inv@b

In [12]:
w = multivariate_regression(x,y)
w

array([ 3.83801029e+02, -3.63808834e+00, -1.11681568e-01])

In [13]:
x_test = [1,25,1000]
y_test = w.T @ x_test
y_test

np.float64(181.16725241027183)

In [14]:
x_interactive = x[:,1]*x[:,2]
x_new = np.column_stack((x,x_interactive))
x_new

array([[1.0000e+00, 1.6000e+00, 8.5100e+02, 1.3616e+03],
       [1.0000e+00, 1.5500e+01, 8.1600e+02, 1.2648e+04],
       [1.0000e+00, 2.2000e+01, 1.0580e+03, 2.3276e+04],
       [1.0000e+00, 4.3000e+01, 1.2010e+03, 5.1643e+04],
       [1.0000e+00, 3.3000e+01, 1.3570e+03, 4.4781e+04],
       [1.0000e+00, 4.0000e+01, 1.1150e+03, 4.4600e+04]])

In [15]:
w_new = multivariate_regression(x_new,y)
w_new

array([ 4.83966183e+02, -7.65603415e+00, -2.22115334e-01,  4.08697965e-03])

In [16]:
x_test_2 = [1,25,1000,2500]
y_test_2 = w_new.T @ x_test_2
y_test_2

np.float64(80.66744428842905)