In [3]:
import numpy as np

In [4]:
A = np.random.rand(200,10)
A

array([[0.80332785, 0.33278803, 0.01259762, ..., 0.11179553, 0.23219086,
        0.39751872],
       [0.63692489, 0.42816344, 0.34899615, ..., 0.78725214, 0.82328455,
        0.82707912],
       [0.44336005, 0.46360554, 0.6397029 , ..., 0.55448875, 0.83248235,
        0.65516026],
       ...,
       [0.69079651, 0.64009846, 0.54577086, ..., 0.78887843, 0.91188838,
        0.54216919],
       [0.45561426, 0.23679573, 0.21471136, ..., 0.77537631, 0.56247613,
        0.30497271],
       [0.92488747, 0.14115744, 0.90294715, ..., 0.84863237, 0.14205131,
        0.93068403]])

  قطعه کد زیر  میانگین هر ستون را بدست میاورد و یک آرایه با ده مقدار خروجی میدهد

In [5]:
mu = np.zeros(A.shape[1])


for i in range(A.shape[0]):
    mu += A[i]

mu /= A.shape[0]
mu

array([0.5060734 , 0.50482236, 0.494991  , 0.48226578, 0.51229033,
       0.51282568, 0.50277149, 0.50759005, 0.47795187, 0.49149777])

 و در کد زیر اختلاف هر خانه با میانگین ستون متناظر در آن را بدست میاورد

In [6]:
B = np.zeros_like(A)
for i in range(A.shape[0]):
    B[i] = A[i] - mu
B

array([[ 0.29725445, -0.17203433, -0.48239338, ..., -0.39579452,
        -0.24576101, -0.09397904],
       [ 0.13085149, -0.07665892, -0.14599486, ...,  0.27966209,
         0.34533268,  0.33558135],
       [-0.06271335, -0.04121682,  0.14471189, ...,  0.0468987 ,
         0.35453048,  0.1636625 ],
       ...,
       [ 0.18472311,  0.1352761 ,  0.05077986, ...,  0.28128838,
         0.4339365 ,  0.05067142],
       [-0.05045914, -0.26802663, -0.28027964, ...,  0.26778625,
         0.08452426, -0.18652506],
       [ 0.41881407, -0.36366492,  0.40795615, ...,  0.34104232,
        -0.33590056,  0.43918626]])

 equivalent program without loops just in a single line of code

In [9]:
diff = A - A.mean(axis=0)

diff

array([[ 0.29725445, -0.17203433, -0.48239338, ..., -0.39579452,
        -0.24576101, -0.09397904],
       [ 0.13085149, -0.07665892, -0.14599486, ...,  0.27966209,
         0.34533268,  0.33558135],
       [-0.06271335, -0.04121682,  0.14471189, ...,  0.0468987 ,
         0.35453048,  0.1636625 ],
       ...,
       [ 0.18472311,  0.1352761 ,  0.05077986, ...,  0.28128838,
         0.4339365 ,  0.05067142],
       [-0.05045914, -0.26802663, -0.28027964, ...,  0.26778625,
         0.08452426, -0.18652506],
       [ 0.41881407, -0.36366492,  0.40795615, ...,  0.34104232,
        -0.33590056,  0.43918626]])