In [1]:
import numpy as np

In [25]:
A = np.random.rand(200,10)
A

array([[0.42182111, 0.65702143, 0.61189952, ..., 0.26119339, 0.50784076,
        0.51852971],
       [0.95911023, 0.93472415, 0.17668131, ..., 0.43905397, 0.14574445,
        0.06423223],
       [0.8900335 , 0.18574053, 0.36010637, ..., 0.47249231, 0.06362321,
        0.81561512],
       ...,
       [0.08907781, 0.36996621, 0.21949382, ..., 0.41591315, 0.77468406,
        0.65432109],
       [0.24896549, 0.33756286, 0.41741887, ..., 0.70359798, 0.1552979 ,
        0.09060584],
       [0.83679128, 0.43595767, 0.98099181, ..., 0.497859  , 0.67416984,
        0.28451108]])

  قطعه کد زیر  میانگین هر ستون را بدست میاورد و یک آرایه با ده مقدار خروجی میدهد

In [20]:
mu = np.zeros(A.shape[1])


for i in range(A.shape[0]):
    mu += A[i]

mu /= A.shape[0]
mu

array([0.49946126, 0.501526  , 0.4976079 , 0.47504681, 0.48527017,
       0.47971461, 0.48097588, 0.55768359, 0.52230759, 0.50240806])

 و در کد زیر اختلاف هر خانه با میانگین ستون متناظر در آن را بدست میاورد

In [24]:
B = np.zeros_like(A)
for i in range(A.shape[0]):
    B[i] = A[i] - mu
B

array([[-0.1644816 , -0.2489968 , -0.1807414 , ..., -0.47860931,
        -0.42436966, -0.02189243],
       [-0.49020897,  0.10920266, -0.44280262, ..., -0.54185672,
        -0.1969725 , -0.10751783],
       [-0.28036458,  0.05631684,  0.35346428, ...,  0.09646414,
         0.27009965, -0.05442434],
       ...,
       [ 0.36267464,  0.37385099, -0.19474722, ...,  0.21673206,
         0.00867591,  0.43872229],
       [-0.12597815,  0.01580397,  0.22608281, ..., -0.08875734,
         0.16753711, -0.10453568],
       [ 0.21385823, -0.35163019, -0.43374987, ...,  0.18046836,
         0.12420449, -0.20996181]])

 equivalent program without loops just in a single line of code

In [23]:
diff = A - A.mean(axis=0)
diff

array([[-0.1644816 , -0.2489968 , -0.1807414 , ..., -0.47860931,
        -0.42436966, -0.02189243],
       [-0.49020897,  0.10920266, -0.44280262, ..., -0.54185672,
        -0.1969725 , -0.10751783],
       [-0.28036458,  0.05631684,  0.35346428, ...,  0.09646414,
         0.27009965, -0.05442434],
       ...,
       [ 0.36267464,  0.37385099, -0.19474722, ...,  0.21673206,
         0.00867591,  0.43872229],
       [-0.12597815,  0.01580397,  0.22608281, ..., -0.08875734,
         0.16753711, -0.10453568],
       [ 0.21385823, -0.35163019, -0.43374987, ...,  0.18046836,
         0.12420449, -0.20996181]])