In [46]:
import numpy as np
import torch

In [47]:
l = [1,2,3]
l

[1, 2, 3]

In [48]:
a=np.array(l)
a

array([1, 2, 3])

In [49]:
a[2]=300
a

array([  1,   2, 300])

In [50]:
t = torch.tensor(l)
t

tensor([1, 2, 3])

In [51]:
display(type(l))
display(type(a))
display(type(t))


list

numpy.ndarray

torch.Tensor

In [52]:
t1 = torch.tensor(a)
t2 = torch.from_numpy(a)
a[0] = 100
print(a)
print(t1)
print(t2)

[100   2 300]
tensor([  1,   2, 300])
tensor([100,   2, 300])


In [53]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
t = torch.zeros(10)
t

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
a.dtype

dtype('float64')

In [56]:
t.dtype

torch.float32

In [57]:
a[2] = 4
a

array([0., 0., 4., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
t[2] = 4
t

tensor([0., 0., 4., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [60]:
a = np.ones(10)* -20
a

array([-20., -20., -20., -20., -20., -20., -20., -20., -20., -20.])

In [61]:
t = torch.ones(10) * 40
t

tensor([40., 40., 40., 40., 40., 40., 40., 40., 40., 40.])

In [62]:
a = np.full(10 , 222)
a

array([222, 222, 222, 222, 222, 222, 222, 222, 222, 222])

In [63]:
a = np.full((10,), 222)
a

array([222, 222, 222, 222, 222, 222, 222, 222, 222, 222])

In [64]:
t = torch.full((10,), 222)
t

tensor([222, 222, 222, 222, 222, 222, 222, 222, 222, 222])

In [65]:
# t = torch.full(10, 222)
# t

In [66]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a.dtype

dtype('int64')

In [68]:
t = torch.arange(10)
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
t.dtype

torch.int64

## basic properties

In [82]:
a = np.ones(10000, dtype=np.float64)
a = np.ones((10,10), dtype=np.float64)
t = torch.ones(10000, dtype=torch.float64)
display(a)
display(type(a))
display(type(t))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

numpy.ndarray

torch.Tensor

In [83]:
display(len(a))
len(t)


10

10000

In [84]:
display(a.shape)
display(t.shape)
display(t.size())

display(a.shape[0])
display(t.shape[0])
display(t.size(0))

(10, 10)

torch.Size([10000])

torch.Size([10000])

10

10000

10000

In [85]:
display(a.size) # number of elements
display(t.numel()) # number of elements

100

10000

In [90]:
a.ndim

2

In [91]:
t.ndim

1

In [88]:
a.dtype

dtype('float64')

In [89]:
display(a.itemsize) # each item has how many bytes
display(t.itemsize)
display(t.element_size())


8

8

8

In [94]:
display(a.nbytes) # itemsize * number of elements
display(a.itemsize * a.size)
display(t.itemsize * t.numel())

800

800

80000

## list vs numpy arrays

In [95]:
l1 = [1,2,3]
l2 = [4,5,6]
a1 = np.array(l1)
a2 = np.array(l2)
display(l1+l2)
display(a1+a2)


[1, 2, 3, 4, 5, 6]

array([5, 7, 9])

## Data types

In [96]:
a = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.int64)
b = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.int32)
c = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.int16)
d = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.int8)
e = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.uint8)
print(a.itemsize, b.itemsize, c.itemsize, d.itemsize, e.itemsize)
print(a.nbytes, b.nbytes, c.nbytes, d.nbytes, e.nbytes)

8 4 2 1 1
80 40 20 10 10


In [99]:
d-4

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6], dtype=int8)

In [98]:
e-4

array([253, 254, 255,   0,   1,   2,   3,   4,   5,   6], dtype=uint8)

In [101]:
f = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.float32)
g = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.float64)
h = np.array([1,2,3,4,5,6,7,8,9,10], dtype=np.float128)
print(f.itemsize, g.itemsize, h.itemsize)
print(f.nbytes, g.nbytes, h.nbytes)

4 8 16
40 80 160


In [102]:
l = np.array([False,True,True])
l.dtype

dtype('bool')

In [103]:
l = np.array([0,1,1], dtype=np.bool)
l.dtype

dtype('bool')

In [104]:
l.nbytes

3

## Basic operations